language: php
php:
  - '5.6'

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - phpunit
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$SSH_HOST "cd $DEPLOY_PATH && git pull && php artisan migrate:refresh --seed"
