language: php
php:
  - '5.6'

before_install:
  - echo "" > ~/.ssh/id_rsa
  - openssl aes-256-cbc -K $encrypted_9431a6898e0f_key -iv $encrypted_9431a6898e0f_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - composer self-update
  - composer config --global github-oauth.github.com $GITHUB_TOKEN
  - chmod 600 ~/.ssh/id_rsa

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - phpunit
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$SSH_HOST "cd $DEPLOY_PATH && git pull && php artisan migrate:refresh --seed"
